modLoader="javafml"
#loaderVersion="[${loader_version},)"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/GregTech-Intergalactical/GregTech/issues"

[[mods]]
modId="gti"
#version="${version}"
version="0.0.1"
displayName="GregTech"
#updateJSONURL="http://myurl.me/"
displayURL="https://github.com/GregTech-Intergalactical/GregTech"
#logoFile="gregtech.png"
credits="GregoriusTechneticies for his previous versions of GregTech. And the current GregTech community for suggestions and ideas."
authors="Muramasa, Rongmario"
description='''The Approved Continuation. Rewrite. And Re-envisioning of GregTech 5'''
[[dependencies.gti]]
    modId="antimatter"
    mandatory=true
    #versionRange="[${antimatter_version},)"
    versionRange="0.0.1"
    ordering="AFTER"
    side="BOTH"
[[dependencies.gti]]
    modId="forge"
    mandatory=true
    #versionRange="[${forge_version},)"
    versionRange="31.0.1"
    ordering="NONE"
    side="BOTH"
[[dependencies.gti]]
    modId="minecraft"
    mandatory=true
    #versionRange="[${minecraft_version}]"
    versionRange="1.15.2"
    ordering="NONE"
    side="BOTH"